#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload >/dev/null 2>&1 || true
    if [ "$1" = "remove" ]; then
        systemctl disable armonix.service >/dev/null 2>&1 || true
    fi
fi

if [ "$1" = "purge" ]; then
    deluser --system armonix >/dev/null 2>&1 || true
    rm -rf /var/lib/armonix
fi

exit 0
