#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
        systemctl stop armonix.service >/dev/null 2>&1 || true
    fi
fi

exit 0
