#!/usr/bin/env python3
import os
import sys

BASE_DIR = "/usr/lib/armonix"

if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from main import main


if __name__ == "__main__":
    os.environ.setdefault("PYTHONUNBUFFERED", "1")
    main(["--headless", "--disable-vnc", *sys.argv[1:]])
